import Header from "./components/Header/Header";
import "./globals.css";

export const metadata = {
  title: "NEXT-PRACTICE-MUSCLE-APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        <Header />

        {children}

        <footer>footer</footer>
      </body>
    </html>
  );
}
